In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('C:\\Users\\ASUS\\Desktop\\Road to Data Scientist\\ML training\\titanic\\tested.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
df['Survived'].value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [8]:
df.drop(['PassengerId', 'Name', 'Cabin' , 'Embarked', 'SibSp', 'Parch','Ticket'], axis = 'columns', inplace = True)

In [9]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [11]:
target = df.Survived 
inputs = df.drop(['Survived'] , axis = 'columns')

In [13]:
dummies = pd.get_dummies(inputs.Sex)
dummies = dummies.astype(int)
dummies.head()

   female  male
0       0     1
1       1     0
2       0     1
3       0     1
4       1     0

In [14]:
inputs = pd.concat([inputs,dummies],axis = 'columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  34.5   7.8292       0     1
1       3  female  47.0   7.0000       1     0
2       2    male  62.0   9.6875       0     1
3       3    male  27.0   8.6625       0     1
4       3  female  22.0  12.2875       1     0

In [15]:
inputs.drop('Sex',axis='columns',inplace = True)
inputs.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

In [17]:
inputs.Age[:20]

0     34.5
1     47.0
2     62.0
3     27.0
4     22.0
5     14.0
6     30.0
7     26.0
8     18.0
9     21.0
10     NaN
11    46.0
12    23.0
13    63.0
14    47.0
15    24.0
16    35.0
17    21.0
18    27.0
19    45.0
Name: Age, dtype: float64

In [18]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

In [21]:
pd.isnull(inputs).sum()

Pclass    0
Age       0
Fare      1
female    0
male      0
dtype: int64

In [33]:
#inputs.dropna(subset=['Fare'], inplace=True)

In [27]:
pd.isnull(inputs).sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [31]:
target = target.iloc[:-1]

In [32]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(inputs , target , test_size = 0.2)

In [34]:
len(X_train)

333

In [38]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [39]:
model.fit(X_train, y_train)

GaussianNB()

In [40]:
model.score(X_test , y_test)

0.7380952380952381